apiVersion: apps/v1
kind: Deployment
metadata:
  name: lb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lb
  template:
    metadata:
      labels:
        app: lb
    spec:
      containers:
        - name: lb
          image: lb:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: BACKENDS_SERVICE
              value: "backend-headless"
          ports:
            - containerPort: 8000
